config/routes.rb
Rails.application.routes.draw do
  resources :homes
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get '/graduation', to: 'courses#graduation', as: 'graduation'
  get '/graduation_status/:student_id', to: 'courses#graduation_status', as: 'graduation_status'
  resources :courses do

    member do
      post 'enroll', to: 'enrollments#create'
    end
  
  end
  resources :enrollments
  resources :users
  patch '/profile', to: 'profiles#update', as: 'update_profile'
  root to: "homes#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :enrollments
  has_many :users, through: :enrollments
  

  def self.search(search)
    if search
      where('title LIKE ?', "%#{search}%")
    else
      all
    end
  end

  
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :course

end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one :profile
         accepts_nested_attributes_for :profile
         has_many :enrollments
         has_many :courses, through: :enrollments


   after_create :create_finance_account
  

  private
   
   def create_finance_account
    student_id = 'c' + DateTime.now.strftime('%H%M%S')
    FinanceService.new.create_library_account(student_id)
    response = FinanceService.new.create_account( student_id, name)
    self.update(:student_id => student_id)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :password_confirmation, :name)
    end
  
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:email, :password, :password_confirmation, :current_password, :name)
    end
  end
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.search(params[:search])
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  def graduation
    response = FinanceService.new.graduation(student_id: current_user.student_id)
    
    # Check if the student has outstanding invoices
    respond_to do |format|
      if response.code == 200
        format.html { redirect_to graduation_status_path(current_user.student_id), notice: "You have an outstanding invoice, So you are not eligible for graduation" }
      else 
        format.html { redirect_to graduation_status_path(current_user.student_id), notice: "No outstanding invoices found. You are  elligible for graduation." }
      end
    end
  end
  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description, :price)
    end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @enrollment   = current_user.enrollments.all
  end 

  def create
    course = Course.find(params[:id])
    course.update(reference_no: SecureRandom.hex(4))
    current_user.courses << course
   
   FinanceService.new.create_invoice(student_id: current_user.student_id, course_code: course.reference_no, price: course.price)
     
    redirect_to course, notice: 'Enrollment successful.'
  end

  def destroy
    course = Course.find(params[:id])
    current_user.courses.delete(course)

    redirect_to course, notice: 'Enrollment removed.'
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: %i[ show edit update destroy ]

  # GET /homes or /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1 or /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes or /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to home_url(@home), notice: "Home was successfully created." }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1 or /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to home_url(@home), notice: "Home was successfully updated." }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1 or /homes/1.json
  def destroy
    @home.destroy

    respond_to do |format|
      format.html { redirect_to homes_url, notice: "Home was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def home_params
      params.fetch(:home, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @profiles = User.all
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
     @user = current_user
    if @user.update(profile_params)
      redirect_to @user, notice: "Profile updated successfully."
    else
      render :edit
    end
  end


  def destroy
    @profile = current_user.profile
    @profile.destroy
    redirect_to profiles_path, notice: "Profile deleted successfully."
  end

  private

  def set_profile
    @profile = current_user.profile
  end

  def profile_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true, html: { class: "needs-validation", novalidate: "" }) do |form| %>
  <% if course.errors.any? %>
    <div class="alert alert-danger">
      <h4 class="alert-heading"><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h4>
      <ul>
        <% course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control", rows: 3, required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :price, class: "form-label" %>
    <%= form.number_field :price, step: 0.01, class: "form-control", required: true %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/graduation_status.html.erb
<p id="notice" class="alert alert-info"><%= notice %></p>

app/views/courses/index.html.erb
<p id="notice" class="alert alert-info"><%= notice %></p>


  <div class="row pull-right">
      <%= form_with(url: courses_path, method: :get, local: true) do |form| %>
      <div class="col-md-8">
        <%= form.text_field :search, placeholder: "Search courses...", class:"form-control" %>
      </div>
      <div class="col-md-4">
        <%= form.submit "Search", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  
<h1 class="mb-4">Courses</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= course.description %></td>
        <td><%= number_to_currency(course.price) %></td>
        <td><%= link_to 'Show', course, class: "btn btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<% if notice %>
  <div class="alert alert-info"><%= notice %><p><%= @course.reference_no if current_user.courses.last.enrollment_ids %></p></div>
<% end %>

<div class="mt-4">
  <h2><%= @course.title %></h2>
  <p class="text-muted"><%= @course.description %></p>
  <h4 class="text-success"><%= number_to_currency(@course.price) %></h4>
</div>

<div class="mt-4">
  <%= button_to 'Enroll', enroll_course_path(@course), method: :post, class: 'btn btn-primary' %>
</div>

app/views/enrollments/index.html.erb
<p id="notice" class="alert alert-info"><%= notice %></p>
<% if @enrollment.present? %>
<h1 class="mb-4">My Enrollment</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Reference No</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrollment.each do |enrollment| %>
      <tr>
        <td><%= enrollment.course.title %></td>
        <td><%= enrollment.course.description %></td>
        <td><%= enrollment.course.reference_no %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <h1>No enrollments found.</h1>
<% end %>

app/views/homes/_form.html.erb
<%= form_with(model: home) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
        <% home.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome <%= current_user.name %></h1>

<h4> You can register as many courses as you want from this portal</h4>
 

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Student</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <nav class="navbar navbar-dark bg-primary text-light">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "Student Portal", homes_path, class:"navbar-brand" %> 
          </div>
      
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to "Home", homes_path %>  </li>
              <li><%= link_to "All courses", courses_path  %></li>
              <li><%= link_to "Student Profile",  user_path(current_user)  %></li>
              <li><%= link_to "Graduation", graduation_path %></li>
              <li><%= link_to "My Enrollment", enrollments_path %></li>
            </ul>
            
            <ul class="nav navbar-nav navbar-right">
              <form class="navbar-form navbar-left">
                <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "btn btn-primary" %>
              </form>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/profiles/edit.html.erb
<%= form_for(current_user.profile,  url: update_profile_path(current_user.profile)) do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :surname %>
    <%= f.text_field :surname, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= f.submit "Update Profile", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/profiles/show.html.erb
<h1>student profile</h1>

<p>
  First name: <%= @profile.name %>
</p>

<p>
  Last name: <%= @profile.surname %>
</p>


<%= link_to "Edit", edit_profile_path(current_user), class: "btn btn-primary" %>
<%= link_to "Destroy", @profile, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_with model: @user, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <br />
    <%= form.submit  class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Student Id:</strong>
  <%= @user.student_id %>
</p>

<%= link_to 'Edit', edit_user_path(@user), class: "btn btn-primary" %> 